"""
§11 — queue/worker layer, plus the parts of §3/§13 that live at the worker
level: the one-open-question conflict handling, NotificationFailed
emission (§13), and the scheduled expiry job that resumes a paused
origin-module run when a member never replies in time.
"""
from __future__ import annotations

import asyncio
import logging
from collections import defaultdict

from .channel_policy import get_policy, send_with_fallback
from .events import emit_event
from .models import NotificationRequest
from .realtime import push_live_update
from .storage import OpenPendingResponseConflict, db
from .summary import generate_summary

logger = logging.getLogger("notification.worker")

# In-memory "queued behind pending" holding area (§3's conflict-handling
# note) — a real deployment would persist this in `notifications` with
# status=QUEUED_BEHIND_PENDING and re-scan on a schedule; this mirrors that
# with an explicit retry hook instead, since we already have one (resolution
# time is exactly when the next queued request should be attempted).
# Stores (request, notification_record_id) — the message was ALREADY
# delivered on the first attempt (that part succeeded); only the
# create_pending_response registration is what needs a second try, so the
# retry must NOT re-run the whole pipeline (that would hit the idempotency
# check and silently no-op, which is exactly the bug this comment used to
# not warn about).
_queued_behind_pending: dict[str, list[tuple]] = defaultdict(list)


def _idempotency_key(request: NotificationRequest, channel: str) -> str:
    return f"{request.itinerary_id}:{request.event_id}:{channel}"


async def process_notification(request: NotificationRequest) -> None:
    print("=" * 60)
    print("WORKER STARTED")
    print("Event:", request.event_id)
    print("Type :", request.event_type)
    print("=" * 60)
    prefs = await db.get_member_prefs(request.member_id)
    policy = get_policy(request.event_type)

    # idempotency check happens on the PRIMARY channel's key — if that's
    # already recorded, this exact event was already processed
    primary_key = _idempotency_key(request, policy["primary"])
    if await db.exists_by_idempotency_key(primary_key):
        logger.info(f"Skipping already-processed event_id={request.event_id} (idempotent replay)")
        return

    summary, generated_by = await generate_summary(request.change_diff, policy["primary"])
    print("Summary generated:")
    print(summary)
    print("Generated by:", generated_by)
    delivered, channel_used = await send_with_fallback(request, summary, prefs)
    print("Delivered:", delivered)
    print("Channel:", channel_used)

    idempotency_key = _idempotency_key(request, channel_used or policy["primary"])
    record = await db.record_notification(
        itinerary_id=request.itinerary_id, member_id=request.member_id,
        origin_module=request.origin_module, event_type=request.event_type,
        channel=channel_used or policy["primary"], content=summary, generated_by=generated_by,
        status="DELIVERED" if delivered else "FAILED", requires_response=request.requires_response,
        idempotency_key=idempotency_key)
    
    if record is None:
        return  # idempotent replay caught at the record layer too

    if not delivered:
        if policy["urgency"] in ("high", "critical"):
            # exhausted every fallback channel and still not confirmed —
            # not this module's problem to swallow silently (§13)
            await emit_event("NotificationFailed", itinerary_id=request.itinerary_id,
                              member_id=request.member_id, origin_module="NOTIFICATION",
                              failed_event_type=request.event_type)
        await push_live_update(request.member_id, {"event_type": request.event_type,
                                                     "status": "FAILED", **request.change_diff.model_dump()})
        
        return

    if request.requires_response:
        try:
            await db.create_pending_response(
                notification_id=record.id, member_id=request.member_id, itinerary_id=request.itinerary_id,
                origin_module=request.origin_module, origin_thread_id=request.origin_thread_id or "",
                callback_event_type=request.callback_event_type or "",
                expires_in_seconds=request.expires_in_seconds)
        except OpenPendingResponseConflict:
            # §3's real UX tradeoff: don't guess which open question a reply
            # answers — queue this one instead, honest and unambiguous
            logger.info(f"member={request.member_id} already has an open question — "
                        f"queuing event_id={request.event_id} behind it")
            await db.update_notification_status(record.id, "QUEUED_BEHIND_PENDING")
            _queued_behind_pending[request.member_id].append((request, record.id))

    await push_live_update(request.member_id, {"event_type": request.event_type,
                                                 "status": "DELIVERED", "channel": channel_used,
                                                 **request.change_diff.model_dump()})
    print("Notification processing complete.")

async def retry_queued_for_member(member_id: str) -> None:
    """Call this right after a member's open pending response resolves
    (approve/deny/SMS reply) — the natural trigger point for re-attempting
    whatever got queued behind it.

    Only re-attempts the create_pending_response registration, NOT the
    whole send pipeline — the notification content was already delivered
    on the first attempt (that part succeeded fine); re-running
    process_notification from scratch would hit the idempotency check and
    silently no-op instead of actually registering the pending response."""
    queued = _queued_behind_pending.pop(member_id, [])
    for request, record_id in queued:
        try:
            await db.create_pending_response(
                notification_id=record_id, member_id=request.member_id, itinerary_id=request.itinerary_id,
                origin_module=request.origin_module, origin_thread_id=request.origin_thread_id or "",
                callback_event_type=request.callback_event_type or "",
                expires_in_seconds=request.expires_in_seconds)
            await db.update_notification_status(record_id, "DELIVERED")
            await push_live_update(request.member_id, {"event_type": request.event_type,
                                                         "status": "DELIVERED",
                                                         **request.change_diff.model_dump()})
        except OpenPendingResponseConflict:
            # still blocked (e.g. a third request queued in behind this one) —
            # put it back and try again on the next resolution
            _queued_behind_pending[member_id].append((request, record_id))


async def expire_stale_pending_responses() -> None:
    """Scheduled job (run this on an interval, e.g. every 60s) — resumes a
    paused origin-module run with a 'TIMEOUT' response when a member never
    replies in time, instead of leaving that run paused forever. The
    origin module's own routing decides what TIMEOUT means for it (e.g.
    the hotel module falls through coverage-verification timeouts to
    CONFIRMED_NOT_COVERED, but escalates on an approval timeout rather
    than silently auto-approving)."""
    expired = await db.find_expired_unresolved_pending_responses()
    for pending in expired:
        await db.mark_pending_response_resolved(pending.notification_id)
        await emit_event(pending.callback_event_type, thread_id=pending.origin_thread_id,
                          response="TIMEOUT", origin_module=pending.origin_module)
        await retry_queued_for_member(pending.member_id)


async def notification_worker(queue: asyncio.Queue) -> None:
    """Separate-process worker loop. In this in-memory build, `queue` is an
    asyncio.Queue standing in for the Redis list + blpop the doc specifies
    — swap for `redis.blpop('notification_queue', ...)` for the real
    deployment; process_notification() itself doesn't change either way."""
    while True:
        request: NotificationRequest = await queue.get()
        try:
            await process_notification(request)
        except Exception:
            logger.exception(f"process_notification failed for event_id={request.event_id}")
        finally:
            queue.task_done()
